<?php


class ClassA extends AbstractClass
{
    public function mustDefine($optional = 'optional property.') : string
    {
        echo __CLASS__.' '.__FUNCTION__.' with '.$optional.PHP_EOL;
        return 'Do something with this.';
    }

    public function optionalMethod()
    {
        //parent::optionalMethod(); // TODO: Change the autogenerated stub
        echo __CLASS__.' '.__FUNCTION__.PHP_EOL;
    }
}